apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: {{ .Release.Name }}-filelogger-buildconfig
spec:
  triggers:
    - type: "ConfigChange"
  source:
    git: 
      uri: https://github.com/carstenmichel/gofilecontentlogger.git
      ref: main
  strategy:
    type: Docker
  output:
    to:
      kind: ImageStreamTag
      name: '{{ .Release.Name }}-filelogger-is:latest'